[versions]
junit = "6.0.2"

[libraries]
junit-api = {module = "org.junit.jupiter:junit-jupiter-api", version.ref="junit"}
junit-engine = {module = "org.junit.jupiter:junit-jupiter-engine", version.ref="junit"}

[bundles]


[plugins]
gitSemVer = "org.danilopianini.git-sensitive-semantic-versioning-gradle-plugin:7.0.12"